name: Push components to Espressif Component Registry

on:
  push:
    branches:
      - main

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Upload components to component registry
        uses: espressif/github-actions/upload_components@master
        with:
          directories: "azure-iot-kit-sensors;azure-iot-middleware-freertos;azure-sdk-for-c;coreMQTT;sample-azure-iot"
          namespace: "espressif"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}